version: '3'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./restorio-gateway/traefic.yaml:/etc/traefik/traefik.yaml 
      - ./restorio-gateway/dynamic.yaml:/etc/traefik/dynamic.yaml
    
  auth:
    container_name: restorio-auth
    build: ./restorio-auth
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SECRET_ACCESS: BcU8q58BtgWzIZ7KfjuQgf9YIEIbh8d/Y2EGPuh8Ui4=
      SECRET_REFRESH: cM4hNZ9z6uS49Q7Uo8Z7I0TvGYoJaCOhWwuY6U9D7QY=
      POSTGRES_CONFIG: host=postgres user=postgres password=postgres dbname=postgres port=5432 sslmode=disable
  
  telegram:
    container_name: restorio-telegram
    build: ./restorio-telegram
    depends_on:
      - postgres
    environment:
      BOT_TOKEN: 8082597348:AAGnqiXFaY7z6MsJQOGb3Mk8TcFRCwNkWqA
      POSTGRES_CONFIG: host=postgres user=postgres password=postgres dbname=postgres port=5432 sslmode=disable

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  frontend:
    build:
      context: ./frontend/react_front
      dockerfile: Dockerfile
    volumes:
      - ./frontend/react_front:/app
      - /app/node_modules
    ports:
      - "3000:3000"  
      - "19000:19000"  
      - "19001:19001"  
    environment:
      - NODE_ENV=development
    command: npm start


volumes:
  postgres_data:
