name: Build and Run Docker Compose

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-from-app1, trigger-from-app2] 

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docker-compose-repo
        uses: actions/checkout@v4
        with:
          path: docker-compose-repo

      - name: Checkout app1
        uses: actions/checkout@v4
        with:
          repository: developeerz/restorio-gateway
          path: docker-compose-repo/restorio-gateway
          token: ${{ secrets.ORG_TOKEN }}

      - name: Checkout app2
        uses: actions/checkout@v4
        with:
          repository: developeerz/restorio-auth
          path: docker-compose-repo/restorio-auth
          token: ${{ secrets.ORG_TOKEN }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose
        working-directory: docker-compose-repo
        run: |
          docker-compose up -d --build
