name: Build and Push to GHCR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - name: Clone and Build
        uses: ./.github/actions/clone-and-build
        with:
          repo-list: ${{ vars.REPO_LIST }}
          checkout-path: '.'
          compose-file: './docker-compose.yaml'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker Images
        run: |
          docker compose -f docker-compose.yaml push

